{"version":3,"sources":["fetchWithNetworkError.js"],"names":["NetworkError","require","module","exports","fetchWithNetworkError","fetch","catch","err","name"],"mappings":";;AAAA,MAAMA,YAAY,GAAGC,OAAO,CAAC,gBAAD,CAA5B;AAEA;AACA;AACA;;;AACAC,MAAM,CAACC,OAAP,GAAiB,SAASC,qBAAT,GAA4C;AAC3D,SAAOC,KAAK,CAAC,YAAD,CAAL,CACJC,KADI,CACGC,GAAD,IAAS;AACd,QAAIA,GAAG,CAACC,IAAJ,KAAa,YAAjB,EAA+B;AAC7B,YAAMD,GAAN;AACD,KAFD,MAEO;AACL,YAAM,IAAIP,YAAJ,CAAiBO,GAAjB,CAAN;AACD;AACF,GAPI,CAAP;AAQD,CATD","sourcesContent":["const NetworkError = require('./NetworkError')\n\n/**\n * Wrapper around window.fetch that throws a NetworkError when appropriate\n */\nmodule.exports = function fetchWithNetworkError (...options) {\n  return fetch(...options)\n    .catch((err) => {\n      if (err.name === 'AbortError') {\n        throw err\n      } else {\n        throw new NetworkError(err)\n      }\n    })\n}\n"]}